# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom

Arquivos da aula: https://drive.google.com/drive/folders/1FbDqVq4XLvU85VBlVIMJ73p9oOu6u2-J?usp=drive_link

In [8]:
# Analisar clientes
# se o cliente em questão é 'Bom', 'Ok' ou 'Ruim' (Nota de Crédito dele = Score de Crédito)

# Good = Boa
# Standard = Ok
# Poor = Ruim

# Passo a Passo do projeto
# Passo 0: Entender o Desafio da Empresa
# Passo 1: Importar a Base de Dados
# pip install pandas scikit-learn
import pandas as pd

tabela = pd.read_csv("clientes.csv")

display(tabela)
display(tabela.info())
display(tabela.columns)

# int -> números inteiros
# float -> números com casas decimais
# object -> int -> textos

       id_cliente  mes  ...  emprestimo_credito emprestimo_estudantil
0            3392    1  ...                   1                     0
1            3392    2  ...                   1                     0
2            3392    3  ...                   1                     0
3            3392    4  ...                   1                     0
4            3392    5  ...                   1                     0
...           ...  ...  ...                 ...                   ...
99995       37932    4  ...                   0                     1
99996       37932    5  ...                   0                     1
99997       37932    6  ...                   0                     1
99998       37932    7  ...                   0                     1
99999       37932    8  ...                   0                     1

[100000 rows x 25 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB

None

Index(['id_cliente', 'mes', 'idade', 'profissao', 'salario_anual',
       'num_contas', 'num_cartoes', 'juros_emprestimo', 'num_emprestimos',
       'dias_atraso', 'num_pagamentos_atrasados', 'num_verificacoes_credito',
       'mix_credito', 'divida_total', 'taxa_uso_credito',
       'idade_historico_credito', 'investimento_mensal',
       'comportamento_pagamento', 'saldo_final_mes', 'score_credito',
       'emprestimo_carro', 'emprestimo_casa', 'emprestimo_pessoal',
       'emprestimo_credito', 'emprestimo_estudantil'],
      dtype='object')

In [9]:
# Passo 2:Tratar e Preparar a Base de Dados para a Inteligência artificial

from sklearn.preprocessing import LabelEncoder
import pandas

# Como transformar essas 3 colunas textuais em números?
# profissao, deve ser numérica - algumas profissões: cientista, marceneiro, pedreito, pintor, artista, mecanico

# pode ser feito a partir da seguinte ferramenta:

# LabelEncoder

# ou, pode ser feito manualmente:

# cientista = 1
# marceneiro = 2
# pedreiro = 3
codificador_profissao = LabelEncoder()
tabela["profissao"] = codificador_profissao.fit_transform(tabela["profissao"])

# mix_credito, deve ser numérica
codificador_mix = LabelEncoder()
tabela["mix_credito"] = codificador_mix.fit_transform(tabela["mix_credito"])

# comportamento_pagamento, deve ser numérica
codificador_comportamento = LabelEncoder()
tabela["comportamento_pagamento"] = codificador_comportamento.fit_transform(tabela["comportamento_pagamento"])

# Objetivo: prever a coluna "score_credito", somente esta coluna pode ser textual
display(tabela)

       id_cliente  mes  ...  emprestimo_credito  emprestimo_estudantil
0            3392    1  ...                   1                      0
1            3392    2  ...                   1                      0
2            3392    3  ...                   1                      0
3            3392    4  ...                   1                      0
4            3392    5  ...                   1                      0
...           ...  ...  ...                 ...                    ...
99995       37932    4  ...                   0                      1
99996       37932    5  ...                   0                      1
99997       37932    6  ...                   0                      1
99998       37932    7  ...                   0                      1
99999       37932    8  ...                   0                      1

[100000 rows x 25 columns]

In [10]:
# Passo 3: Criar o Modelo de Previsão ou Modelo de IA -> 'Ruim', 'Ok', 'Boa'
# escolhendo quais colunas serão usadas para treinar o modelo
# y é a coluna que queremos que o modelo calcule
# x são todas as colunas que serão usadas para prever o'score de crédito', a coluna 'id_cliente' não será usada, porque ela é um número de identificação única, mas como cada linha neste contexto é única, não há necessidade de ter um dado como este: ou seja, ele não ajuda na previsão dos modelos que serão criados.
x = tabela.drop(["score_credito", "id_cliente"], axis=1)
y = tabela["score_credito"]

from sklearn.model_selection import train_test_split

# separar os dados em treino e teste. 'treino', será o nome dado para os modelos aprenderem, enquanto 'teste' será o termo usado para verificar se os modelos aprenderam como se espera.
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=1)

In [20]:
# Passo 4: Avaliar e Escolher o Melhor Modelo
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

modelo_arvore = RandomForestClassifier()    # modelo árvore de decisão
modelo_knn = KNeighborsClassifier() # modelo do KNN (nearest neighbors - vizinhos mais próximos)

# treinando os modelos
modelo_arvore.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

# se o modelo utilizar "Ok" em todos os casos, qual seria a acurácia, a precisão do modelo?
contagem_scores = tabela["score_credito"].value_counts()
print(contagem_scores["Standard"] / sum(contagem_scores))

from sklearn.metrics import accuracy_score

# calcular as previsões
previsao_arvore = modelo_arvore.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste.to_numpy())

# começar previsões com 'y_teste'
# para esse score o maior é requerido (maior acurácia, mas há a necessidade de o valor ser maior que o fornecido pelo chute de todas as opções como 'Standard')
print(accuracy_score(y_teste, previsao_arvore))
print(accuracy_score(y_teste, previsao_knn))

# quais as características mais importantes para definir o score de crédito?
colunas = list(x_teste.columns)
importancia = pd.DataFrame(index=colunas, data=modelo_arvore.feature_importances_)
importancia = importancia * 100
print(importancia)

0.53174

c:\Users\AsusPC\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

0.8248
0.7324
                                  0
mes                        3.976338
idade                      4.228358
profissao                  3.258216
salario_anual              5.010987
num_contas                 3.467442
num_cartoes                4.606869
juros_emprestimo           7.917283
num_emprestimos            3.286135
dias_atraso                6.291082
num_pagamentos_atrasados   4.508316
num_verificacoes_credito   4.861719
mix_credito                8.361141
divida_total              11.543392
taxa_uso_credito           5.048286
idade_historico_credito    7.447950
investimento_mensal        4.823344
comportamento_pagamento    2.353521
saldo_final_mes            5.484721
emprestimo_carro           0.715952
emprestimo_casa            0.728024
emprestimo_pessoal         0.704843
emprestimo_credito         0.703297
emprestimo_estudantil      0.672783

In [22]:
# Passo 5: Fazer Novas Previsões
print(previsao_arvore)

['Standard' 'Poor' 'Poor' ... 'Standard' 'Standard' 'Good']